# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d097d66572b915325635e1eac63240c9eef9293d38ba2498755a9605cf93e2c7ac01354b58c8e98fe5e5eecf10d46c3f694626ec11c0aab19f175cc0acb1f896

test:
  secret_key_base: 9ba0055004f719707be84058850833b92536e9ec52d802f3b2117b54a98fc5ec158cdd41ce9ff5bbbd9fd9f08f801d462705b2c2c84db28e8eb67f5744b8ed43

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
